# Generated by Django 5.1.1 on 2025-05-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0015_presidentialround2candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('prezidentiale', 'Alegeri Prezidențiale'), ('prezidentiale_tur2', 'Alegeri Prezidențiale Turul 2'), ('parlamentare', 'Alegeri Parlamentare'), ('locale', 'Alegeri Locale')], max_length=25)),
                ('vote_datetime', models.DateTimeField()),
                ('location_type', models.CharField(choices=[('romania', 'România'), ('strainatate', 'Străinătate')], default='romania', max_length=15)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('voter_age_group', models.CharField(choices=[('18-24', '18-24 ani'), ('25-34', '25-34 ani'), ('35-44', '35-44 ani'), ('45-64', '45-64 ani'), ('65+', '65+ ani')], max_length=10)),
                ('voter_gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.localcandidate')),
                ('parliamentary_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.parliamentaryparty')),
                ('presidential_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.presidentialcandidate')),
                ('presidential_round2_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.presidentialround2candidate')),
            ],
            options={
                'verbose_name': 'Rezultat Vot',
                'verbose_name_plural': 'Rezultate Vot',
                'indexes': [models.Index(fields=['vote_type', 'location_type'], name='rezultate_v_vote_ty_1adefe_idx'), models.Index(fields=['vote_datetime'], name='rezultate_v_vote_da_ecda88_idx'), models.Index(fields=['county', 'city'], name='rezultate_v_county_0bfbde_idx')],
            },
        ),
    ]
