# Generated by Django 5.1.1 on 2025-05-24 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.CharField(choices=[('small', 'Mic (14px)'), ('medium', 'Mediu (16px)'), ('large', 'Mare (18px)'), ('extra_large', 'Extra Mare (22px)')], default='medium', max_length=20)),
                ('contrast_mode', models.CharField(choices=[('normal', 'Normal'), ('high', 'Contrast Ridicat'), ('dark', 'Temă Întunecată')], default='normal', max_length=20)),
                ('animations', models.CharField(choices=[('enabled', 'Activate'), ('reduced', 'Reduse'), ('disabled', 'Dezactivate')], default='enabled', max_length=20)),
                ('focus_highlights', models.BooleanField(default=False, verbose_name='Evidențiere focus')),
                ('extended_time', models.BooleanField(default=False, verbose_name='Timp extins pentru vot')),
                ('simplified_interface', models.BooleanField(default=False, verbose_name='Interfață simplificată')),
                ('audio_assistance', models.BooleanField(default=False, verbose_name='Asistență audio')),
                ('keyboard_navigation', models.BooleanField(default=False, verbose_name='Navigare doar cu tastatura')),
                ('extra_confirmations', models.BooleanField(default=False, verbose_name='Confirmări suplimentare')),
                ('large_buttons', models.BooleanField(default=False, verbose_name='Butoane mari')),
                ('screen_reader_support', models.BooleanField(default=False, verbose_name='Suport cititor de ecran')),
                ('audio_notifications', models.BooleanField(default=False, verbose_name='Notificări audio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setări Accesibilitate',
                'verbose_name_plural': 'Setări Accesibilitate',
            },
        ),
    ]
