# Generated by Django 5.1.1 on 2025-04-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionAnalyticsChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('chart_type', models.CharField(choices=[('line', 'Linie'), ('bar', 'Bare'), ('pie', 'Pie'), ('doughnut', 'Doughnut'), ('radar', 'Radar')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grafic Analitic',
                'verbose_name_plural': 'Grafice Analitice',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.electionanalyticschart')),
            ],
            options={
                'verbose_name': 'Etichetă',
                'verbose_name_plural': 'Etichete',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ChartDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('background_color', models.CharField(blank=True, help_text='Culori separate prin virgulă, ex: #ff6b6b,#5f27cd,#1dd1a1', max_length=255, null=True)),
                ('border_color', models.CharField(blank=True, max_length=50, null=True)),
                ('fill', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.electionanalyticschart')),
            ],
            options={
                'verbose_name': 'Set de Date',
                'verbose_name_plural': 'Seturi de Date',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ChartDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.chartdataset')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.chartlabels')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.electionanalyticschart')),
            ],
            options={
                'verbose_name': 'Punct de Date',
                'verbose_name_plural': 'Puncte de Date',
                'unique_together': {('dataset', 'label')},
            },
        ),
    ]
