# Generated by Django 5.1.1 on 2025-04-22 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_electionanalyticschart_chartlabels_chartdataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='news/opinions/avatars/')),
            ],
            options={
                'verbose_name': 'Autor Opinie',
                'verbose_name_plural': 'Autori Opinii',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('sample_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sondaj',
                'verbose_name_plural': 'Sondaje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinions', to='news.category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='news.opinionauthor')),
            ],
            options={
                'verbose_name': 'Opinie',
                'verbose_name_plural': 'Opinii',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='news.poll')),
            ],
            options={
                'verbose_name': 'Opțiune Sondaj',
                'verbose_name_plural': 'Opțiuni Sondaj',
            },
        ),
    ]
