# Generated by Django 5.1.1 on 2025-04-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_opinionauthor_poll_opinion_polloption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='polloption',
            name='poll',
        ),
        migrations.DeleteModel(
            name='OpinionAuthor',
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
    ]
