# Generated by Django 5.1.1 on 2025-05-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='two_factor_verified',
            field=models.BooleanField(default=False),
        ),
    ]
