# Generated by Django 5.1.1 on 2025-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('parlamentare', 'Alegeri Parlamentare'), ('prezidentiale', 'Alegeri Prezidențiale'), ('locale', 'Alegeri Locale'), ('simulare', 'Simulare Vot')], default='simulare', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setări Vot',
                'verbose_name_plural': 'Setări Vot',
            },
        ),
    ]
