# Generated by Django 5.1.1 on 2025-03-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='votesettings',
            name='vote_type',
            field=models.CharField(choices=[('simulare', 'Simulare'), ('prezidentiale', 'Alegeri Prezidențiale'), ('parlamentare', 'Alegeri Parlamentare'), ('locale', 'Alegeri Locale')], max_length=20),
        ),
    ]
