# Generated by Django 5.1.1 on 2025-03-22 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_votesettings_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('mayor', 'Primar'), ('councilor', 'Consilier Local'), ('county_president', 'Președinte Consiliu Județean'), ('county_councilor', 'Consilier Județean')], max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Candidat Local',
                'verbose_name_plural': 'Candidați Locali',
            },
        ),
        migrations.CreateModel(
            name='VotingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Secție de Vot',
                'verbose_name_plural': 'Secții de Vot',
            },
        ),
        migrations.CreateModel(
            name='LocalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_datetime', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.localcandidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votingsection')),
            ],
            options={
                'verbose_name': 'Vot Local',
                'verbose_name_plural': 'Voturi Locale',
                'unique_together': {('user', 'candidate')},
            },
        ),
    ]
