# Generated by Django 5.1.1 on 2025-03-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_votesettings_updated_at_and_more'),
        ('vote', '0003_localcandidate_votingsection_localvote'),
    ]

    operations = [
    ]
