# Generated by Django 5.1.1 on 2025-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_merge_20250323_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='votesettings',
            name='vote_type',
            field=models.CharField(choices=[('simulare', 'Simulare'), ('prezidentiale', 'Alegeri Prezidențiale'), ('parlamentare', 'Alegeri Parlamentare'), ('locale', 'Alegeri Locale')], max_length=20),
        ),
    ]
