# Generated by Django 5.1.1 on 2025-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_votesettings_updated_at_alter_votesettings_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsection',
            name='address_desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Adresă descriptivă'),
        ),
        migrations.AddField(
            model_name='votingsection',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localitate componentă/Sat aparținător'),
        ),
    ]
