# Generated by Django 5.1.1 on 2025-04-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_votingsection_address_desc_votingsection_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='localvote',
            name='vote_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
