# Generated by Django 5.1.1 on 2025-04-06 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_localvote_vote_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentialCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_nr', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Candidat Prezidențial',
                'verbose_name_plural': 'Candidați Prezidențiali',
                'ordering': ['order_nr', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PresidentialVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_datetime', models.DateTimeField(auto_now_add=True)),
                ('vote_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.presidentialcandidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vot Prezidențial',
                'verbose_name_plural': 'Voturi Prezidențiale',
                'unique_together': {('user', 'vote_reference')},
            },
        ),
    ]
