# Generated by Django 5.1.1 on 2025-04-06 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_presidentialcandidate_presidentialvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentaryParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_nr', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partid Parlamentar',
                'verbose_name_plural': 'Partide Parlamentare',
                'ordering': ['order_nr', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParliamentaryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_datetime', models.DateTimeField(auto_now_add=True)),
                ('vote_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.parliamentaryparty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vot Parlamentar',
                'verbose_name_plural': 'Voturi Parlamentare',
                'unique_together': {('user', 'vote_reference')},
            },
        ),
    ]
