# Generated by Django 5.1.1 on 2025-04-13 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_remove_votesystem_ai_verification_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesystem',
            name='allowed_emails',
            field=models.TextField(blank=True, help_text='Lista de emailuri permise să voteze, separate prin virgulă', null=True),
        ),
        migrations.AddField(
            model_name='votesystem',
            name='require_email_verification',
            field=models.BooleanField(default=False, help_text='Dacă este activat, utilizatorii vor trebui să verifice email-ul înainte de a vota'),
        ),
        migrations.CreateModel(
            name='VoteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('vote_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_tokens', to='vote.votesystem')),
            ],
            options={
                'verbose_name': 'Token vot',
                'verbose_name_plural': 'Token-uri vot',
                'unique_together': {('vote_system', 'email')},
            },
        ),
    ]
