# Generated by Django 5.1.1 on 2025-05-21 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_votesystem_allowed_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentialvote',
            name='voting_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.votingsection'),
        ),
    ]
