# Generated by Django 5.1.1 on 2025-05-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_presidentialvote_voting_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentaryvote',
            name='voting_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.votingsection'),
        ),
    ]
