# Generated by Django 5.1.1 on 2025-05-22 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0014_parliamentaryvote_voting_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentialRound2Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_nr', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('round1_votes', models.IntegerField(default=0, help_text='Numărul de voturi din turul 1')),
                ('round1_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Procentajul din turul 1', max_digits=5)),
            ],
            options={
                'verbose_name': 'Candidat Prezidențial Turul 2',
                'verbose_name_plural': 'Candidați Prezidențiali Turul 2',
                'ordering': ['order_nr', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='votesettings',
            name='vote_type',
            field=models.CharField(choices=[('simulare', 'Simulare'), ('prezidentiale', 'Alegeri Prezidențiale'), ('prezidentiale_tur2', 'Alegeri Prezidențiale Turul 2'), ('parlamentare', 'Alegeri Parlamentare'), ('locale', 'Alegeri Locale')], max_length=20),
        ),
        migrations.CreateModel(
            name='PresidentialRound2Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_datetime', models.DateTimeField(auto_now_add=True)),
                ('vote_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.presidentialround2candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.votingsection')),
            ],
            options={
                'verbose_name': 'Vot Prezidențial Turul 2',
                'verbose_name_plural': 'Voturi Prezidențiale Turul 2',
                'unique_together': {('user', 'vote_reference')},
            },
        ),
    ]
