# Generated by Django 5.1.1 on 2025-04-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Anul alegerilor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriere generală despre alegeri')),
                ('turnout_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prezența la vot (%)')),
                ('total_voters', models.IntegerField(blank=True, null=True, verbose_name='Număr total de alegători')),
            ],
            options={
                'verbose_name': 'An electoral',
                'verbose_name_plural': 'Ani electorali',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Anul evenimentului')),
                ('title', models.CharField(max_length=200, verbose_name='Titlul evenimentului')),
                ('description', models.TextField(verbose_name='Descrierea evenimentului')),
                ('importance', models.IntegerField(choices=[(1, 'Normal'), (2, 'Important'), (3, 'Foarte important')], default=1, verbose_name='Importanța evenimentului')),
            ],
            options={
                'verbose_name': 'Eveniment istoric',
                'verbose_name_plural': 'Evenimente istorice',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PresidentialCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume complet')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data nașterii')),
                ('party', models.CharField(max_length=100, verbose_name='Partid/Alianță politică')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL fotografie')),
                ('biography', models.TextField(verbose_name='Biografie')),
                ('political_experience', models.TextField(blank=True, null=True, verbose_name='Experiență politică')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Educație')),
                ('is_current', models.BooleanField(default=False, verbose_name='Candidat actual (2025)')),
            ],
            options={
                'verbose_name': 'Candidat prezidențial',
                'verbose_name_plural': 'Candidați prezidențiali',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaInfluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('media_type', models.CharField(choices=[('traditional', 'Mass-media tradițională'), ('social', 'Social media'), ('online', 'Media online'), ('other', 'Altele')], max_length=50, verbose_name='Tip de media')),
                ('impact_level', models.IntegerField(choices=[(1, 'Impact redus'), (2, 'Impact mediu'), (3, 'Impact major')], default=2, verbose_name='Nivelul de impact')),
                ('election_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_influences', to='presidential_candidates.electionyear', verbose_name='Anul electoral')),
            ],
            options={
                'verbose_name': 'Influență media',
                'verbose_name_plural': 'Influențe media',
            },
        ),
        migrations.CreateModel(
            name='Controversy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('date', models.DateField(verbose_name='Data')),
                ('impact', models.TextField(blank=True, null=True, verbose_name='Impactul asupra alegerilor')),
                ('election_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controversies', to='presidential_candidates.electionyear', verbose_name='Anul electoral')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controversies', to='presidential_candidates.presidentialcandidate', verbose_name='Candidat implicat')),
            ],
            options={
                'verbose_name': 'Controversă',
                'verbose_name_plural': 'Controverse',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ElectionParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_count', models.IntegerField(blank=True, null=True, verbose_name='Număr de voturi')),
                ('votes_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Procent voturi (%)')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Poziția în clasament')),
                ('round', models.IntegerField(choices=[(1, 'Primul tur'), (2, 'Al doilea tur')], default=1, verbose_name='Turul electoral')),
                ('campaign_slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan de campanie')),
                ('notable_events', models.TextField(blank=True, null=True, verbose_name='Evenimente notabile din campanie')),
                ('election_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='presidential_candidates.electionyear', verbose_name='Anul alegerilor')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='presidential_candidates.presidentialcandidate', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Participare electorală',
                'verbose_name_plural': 'Participări electorale',
                'ordering': ['election_year', 'round', 'position'],
                'unique_together': {('candidate', 'election_year', 'round')},
            },
        ),
    ]
