# Generated by Django 5.1.1 on 2025-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_image',
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='ID Card Image'),
        ),
    ]
