# Generated by Django 5.1.1 on 2025-04-29 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Anul alegerilor locale')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriere generală despre alegerile locale')),
                ('turnout_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prezența la vot (%)')),
                ('total_voters', models.IntegerField(blank=True, null=True, verbose_name='Număr total de alegători')),
            ],
            options={
                'verbose_name': 'Ciclu electoral local',
                'verbose_name_plural': 'Cicluri electorale locale',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='LegislationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('year', models.IntegerField(verbose_name='Anul modificării')),
                ('law_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Număr lege/ordonanță')),
                ('impact', models.TextField(verbose_name='Impactul asupra alegerilor locale')),
            ],
            options={
                'verbose_name': 'Modificare legislativă',
                'verbose_name_plural': 'Modificări legislative',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='LocalElectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Denumire')),
                ('description', models.TextField(verbose_name='Descriere')),
            ],
            options={
                'verbose_name': 'Tip alegeri locale',
                'verbose_name_plural': 'Tipuri alegeri locale',
            },
        ),
        migrations.CreateModel(
            name='ImportantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Anul evenimentului')),
                ('title', models.CharField(max_length=200, verbose_name='Titlul evenimentului')),
                ('description', models.TextField(verbose_name='Descrierea evenimentului')),
                ('importance', models.IntegerField(choices=[(1, 'Normal'), (2, 'Important'), (3, 'Foarte important')], default=1, verbose_name='Importanța evenimentului')),
                ('election_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='local_candidates.electioncycle', verbose_name='Ciclu electoral')),
            ],
            options={
                'verbose_name': 'Eveniment important',
                'verbose_name_plural': 'Evenimente importante',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LocalElectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu regulă')),
                ('description', models.TextField(verbose_name='Descriere regulă')),
                ('since_year', models.IntegerField(verbose_name='Aplicabilă din anul')),
                ('is_current', models.BooleanField(default=True, verbose_name='Regulă curentă')),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='local_candidates.localelectiontype', verbose_name='Tip alegeri')),
            ],
            options={
                'verbose_name': 'Regulă alegeri locale',
                'verbose_name_plural': 'Reguli alegeri locale',
            },
        ),
        migrations.CreateModel(
            name='LocalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Denumire funcție')),
                ('description', models.TextField(verbose_name='Descriere responsabilități')),
                ('importance', models.IntegerField(choices=[(1, 'Importanță redusă'), (2, 'Importanță medie'), (3, 'Importanță majoră')], default=2, verbose_name='Nivel importanță')),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='local_candidates.localelectiontype', verbose_name='Tip alegeri')),
            ],
            options={
                'verbose_name': 'Funcție publică locală',
                'verbose_name_plural': 'Funcții publice locale',
            },
        ),
        migrations.CreateModel(
            name='SignificantCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume complet')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('location', models.CharField(max_length=100, verbose_name='Localitate/Județ')),
                ('party', models.CharField(max_length=100, verbose_name='Partid/Alianță politică')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL fotografie')),
                ('achievement', models.TextField(verbose_name='Realizare notabilă')),
                ('election_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='local_candidates.electioncycle', verbose_name='Ciclu electoral')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='local_candidates.localposition', verbose_name='Funcție')),
            ],
            options={
                'verbose_name': 'Candidat local notabil',
                'verbose_name_plural': 'Candidați locali notabili',
                'ordering': ['-election_cycle__year', 'position', 'name'],
            },
        ),
    ]
