# Generated by Django 5.1.1 on 2025-05-22 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('prezidentiale', 'Alegeri Prezidențiale'), ('prezidentiale_tur2', 'Alegeri Prezidențiale Turul 2'), ('parlamentare', 'Alegeri Parlamentare'), ('locale', 'Alegeri Locale')], max_length=25)),
                ('vote_datetime', models.DateTimeField()),
                ('age_group', models.CharField(choices=[('18-24', '18-24 ani'), ('25-34', '25-34 ani'), ('35-44', '35-44 ani'), ('45-64', '45-64 ani'), ('65+', '65+ ani')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('birth_year', models.IntegerField()),
                ('age_at_vote', models.IntegerField()),
                ('environment', models.CharField(blank=True, choices=[('urban', 'Urban'), ('rural', 'Rural')], max_length=10, null=True)),
                ('location_type', models.CharField(choices=[('romania', 'România'), ('strainatate', 'Străinătate')], default='romania', max_length=15)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistică Vot',
                'verbose_name_plural': 'Statistici Vot',
                'unique_together': {('user', 'vote_type')},
            },
        ),
    ]
