# Generated by Django 5.1.1 on 2025-05-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('prezidentiale', 'Alegeri Prezidențiale'), ('prezidentiale_tur2', 'Alegeri Prezidențiale Turul 2'), ('parlamentare', 'Alegeri Parlamentare'), ('locale', 'Alegeri Locale')], max_length=25)),
                ('location_type', models.CharField(choices=[('romania', 'România'), ('strainatate', 'Străinătate')], max_length=15)),
                ('county', models.CharField(max_length=50, verbose_name='Județ/Țară')),
                ('vote_datetime', models.DateTimeField(verbose_name='Data și ora')),
                ('total_registered', models.IntegerField(default=0, verbose_name='Total înscriși')),
                ('total_voters', models.IntegerField(default=0, verbose_name='Total votanți')),
                ('total_permanent', models.IntegerField(default=0, verbose_name='Total liste permanente')),
                ('total_supplementary', models.IntegerField(default=0, verbose_name='Total liste suplimentare')),
                ('total_mobile', models.IntegerField(default=0, verbose_name='Total urnă mobilă')),
                ('urban_voters', models.IntegerField(default=0, verbose_name='Votanți urban')),
                ('rural_voters', models.IntegerField(default=0, verbose_name='Votanți rural')),
                ('total_men', models.IntegerField(default=0, verbose_name='Total bărbați')),
                ('total_women', models.IntegerField(default=0, verbose_name='Total femei')),
            ],
            options={
                'verbose_name': 'Sumar Prezență',
                'verbose_name_plural': 'Sumare Prezență',
                'unique_together': {('vote_type', 'location_type', 'county', 'vote_datetime')},
            },
        ),
        migrations.CreateModel(
            name='VotingPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50, verbose_name='Județ')),
                ('uat', models.CharField(blank=True, max_length=100, null=True, verbose_name='UAT')),
                ('locality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localitate')),
                ('siruta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cod SIRUTA')),
                ('section_number', models.IntegerField(blank=True, null=True, verbose_name='Numărul secției de votare')),
                ('section_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numele secției de votare')),
                ('environment', models.CharField(choices=[('urban', 'Urban'), ('rural', 'Rural')], max_length=10, verbose_name='Mediu')),
                ('vote_type', models.CharField(choices=[('prezidentiale', 'Alegeri Prezidențiale'), ('prezidentiale_tur2', 'Alegeri Prezidențiale Turul 2'), ('parlamentare', 'Alegeri Parlamentare'), ('locale', 'Alegeri Locale')], max_length=25)),
                ('vote_datetime', models.DateTimeField(verbose_name='Data și ora votului')),
                ('location_type', models.CharField(choices=[('romania', 'România'), ('strainatate', 'Străinătate')], default='romania', max_length=15)),
                ('registered_permanent', models.IntegerField(default=0, verbose_name='Înscriși pe liste permanente')),
                ('voters_permanent', models.IntegerField(default=0, verbose_name='Votanți liste permanente')),
                ('voters_supplementary', models.IntegerField(default=0, verbose_name='Votanți pe liste suplimentare')),
                ('voters_mobile', models.IntegerField(default=0, verbose_name='Votanți cu urnă mobilă')),
                ('men_18_24', models.IntegerField(default=0, verbose_name='Bărbați 18-24 ani')),
                ('men_25_34', models.IntegerField(default=0, verbose_name='Bărbați 25-34 ani')),
                ('men_35_44', models.IntegerField(default=0, verbose_name='Bărbați 35-44 ani')),
                ('men_45_64', models.IntegerField(default=0, verbose_name='Bărbați 45-64 ani')),
                ('men_65_plus', models.IntegerField(default=0, verbose_name='Bărbați 65+ ani')),
                ('women_18_24', models.IntegerField(default=0, verbose_name='Femei 18-24 ani')),
                ('women_25_34', models.IntegerField(default=0, verbose_name='Femei 25-34 ani')),
                ('women_35_44', models.IntegerField(default=0, verbose_name='Femei 35-44 ani')),
                ('women_45_64', models.IntegerField(default=0, verbose_name='Femei 45-64 ani')),
                ('women_65_plus', models.IntegerField(default=0, verbose_name='Femei 65+ ani')),
                ('demographic_data', models.JSONField(blank=True, default=dict, verbose_name='Date demografice detaliate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prezență la Vot',
                'verbose_name_plural': 'Prezență la Vot',
                'indexes': [models.Index(fields=['vote_type', 'location_type'], name='prezenta_vo_vote_ty_cbdd8c_idx'), models.Index(fields=['county', 'vote_datetime'], name='prezenta_vo_county_65befc_idx'), models.Index(fields=['vote_datetime'], name='prezenta_vo_vote_da_454ac8_idx'), models.Index(fields=['environment'], name='prezenta_vo_environ_c23401_idx')],
            },
        ),
    ]
